### ISSUE TITLE
express testing

### ISSUE THREAD

**Issue by olimorri** [olimorri/codehort#179]
On penultimate task I have to enter the terminal command and then press run twice in order for it to pass the test

I believe this is because it is testing two things - the terminal command and the contents of the app.listen

Is it worth getting rid of the terminal command just for the time being? We can come back to it, but if we fix this then the express testing is done and we can focus our efforts onto node and koa

**Comment by VinRanana** [comment]
On it. Will remove for now, then add back in at a later date.

**Comment by VinRanana** [comment]
Sorted in commit #180
